//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lectorxml.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:gaseras.ceoc.com:srvemp:crm:financiacion", ConfigurationName="ServiceReference1.EstCuenta_Out")]
    public interface EstCuenta_Out {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación EstCuenta_Sync no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]


        lectorxml.ServiceReference1.EstCuenta_SyncResponse EstCuenta_Sync(lectorxml.ServiceReference1.EstCuenta_SyncRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://sap.com/xi/WebService/soap1.1", ReplyAction = "*")]
        System.Threading.Tasks.Task<lectorxml.ServiceReference1.EstCuenta_SyncResponse> EstCuenta_SyncAsync(lectorxml.ServiceReference1.EstCuenta_SyncRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gaseras.ceoc.com:srvemp:base")]
    public partial class DT_EstadoCuenta_req : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contratoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
                this.RaisePropertyChanged("contrato");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gaseras.ceoc.com:srvemp:base")]
    public partial class DT_EstadoCuenta_res : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oclFactDataField;
        
        private string onuErrorcodeField;
        
        private string osbErrorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OclFactData {
            get {
                return this.oclFactDataField;
            }
            set {
                this.oclFactDataField = value;
                this.RaisePropertyChanged("OclFactData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OnuErrorcode {
            get {
                return this.onuErrorcodeField;
            }
            set {
                this.onuErrorcodeField = value;
                this.RaisePropertyChanged("OnuErrorcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string osbErrorMessage {
            get {
                return this.osbErrorMessageField;
            }
            set {
                this.osbErrorMessageField = value;
                this.RaisePropertyChanged("osbErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstCuenta_SyncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:gaseras.ceoc.com:srvemp:base", Order=0)]
        public lectorxml.ServiceReference1.DT_EstadoCuenta_req MT_EstadoCuenta_req;
        
        public EstCuenta_SyncRequest() {
        }
        
        public EstCuenta_SyncRequest(lectorxml.ServiceReference1.DT_EstadoCuenta_req MT_EstadoCuenta_req) {
            this.MT_EstadoCuenta_req = MT_EstadoCuenta_req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstCuenta_SyncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:gaseras.ceoc.com:srvemp:base", Order=0)]
        public lectorxml.ServiceReference1.DT_EstadoCuenta_res MT_EstadoCuenta_res;
        
        public EstCuenta_SyncResponse() {
        }
        
        public EstCuenta_SyncResponse(lectorxml.ServiceReference1.DT_EstadoCuenta_res MT_EstadoCuenta_res) {
            this.MT_EstadoCuenta_res = MT_EstadoCuenta_res;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstCuenta_OutChannel : lectorxml.ServiceReference1.EstCuenta_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstCuenta_OutClient : System.ServiceModel.ClientBase<lectorxml.ServiceReference1.EstCuenta_Out>, lectorxml.ServiceReference1.EstCuenta_Out {
        
        public EstCuenta_OutClient() {
        }
        
        public EstCuenta_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstCuenta_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstCuenta_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstCuenta_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lectorxml.ServiceReference1.EstCuenta_SyncResponse lectorxml.ServiceReference1.EstCuenta_Out.EstCuenta_Sync(lectorxml.ServiceReference1.EstCuenta_SyncRequest request) {
            return base.Channel.EstCuenta_Sync(request);
        }
        
        public lectorxml.ServiceReference1.DT_EstadoCuenta_res EstCuenta_Sync(lectorxml.ServiceReference1.DT_EstadoCuenta_req MT_EstadoCuenta_req) {
            lectorxml.ServiceReference1.EstCuenta_SyncRequest inValue = new lectorxml.ServiceReference1.EstCuenta_SyncRequest();
            inValue.MT_EstadoCuenta_req = MT_EstadoCuenta_req;
            lectorxml.ServiceReference1.EstCuenta_SyncResponse retVal = ((lectorxml.ServiceReference1.EstCuenta_Out)(this)).EstCuenta_Sync(inValue);
            return retVal.MT_EstadoCuenta_res;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lectorxml.ServiceReference1.EstCuenta_SyncResponse> lectorxml.ServiceReference1.EstCuenta_Out.EstCuenta_SyncAsync(lectorxml.ServiceReference1.EstCuenta_SyncRequest request) {
            return base.Channel.EstCuenta_SyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<lectorxml.ServiceReference1.EstCuenta_SyncResponse> EstCuenta_SyncAsync(lectorxml.ServiceReference1.DT_EstadoCuenta_req MT_EstadoCuenta_req) {
            lectorxml.ServiceReference1.EstCuenta_SyncRequest inValue = new lectorxml.ServiceReference1.EstCuenta_SyncRequest();
            inValue.MT_EstadoCuenta_req = MT_EstadoCuenta_req;
            return ((lectorxml.ServiceReference1.EstCuenta_Out)(this)).EstCuenta_SyncAsync(inValue);
        }
    }
}
